# Generated by Django 4.2.2 on 2023-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proggramming_language',
            field=models.ManyToManyField(blank=True, through='fossdb.ProjectProgrammingLanguage', to='fossdb.programminglanguage'),
        ),
    ]
