# Generated by Django 4.2.2 on 2023-06-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='owner',
        ),
    ]
