# Generated by Django 4.2.2 on 2023-06-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='types/icons/'),
        ),
    ]
