# Generated by Django 4.2.2 on 2023-06-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossdb', '0002_project_proggramming_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='proggramming_language',
            new_name='programming_language',
        ),
    ]
