# Generated by Django 4.2.2 on 2023-06-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossdb', '0002_alter_tag_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogramminglanguage',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
