# Generated by Django 4.2.2 on 2023-06-28 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fossdb', '0003_alter_projectprogramminglanguage_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tags/icons/'),
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fossdb.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
