# Generated by Django 4.2.2 on 2023-06-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossdb', '0004_alter_tag_icon_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='is_linux',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
