# Generated by Django 4.2.2 on 2023-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossdb', '0005_operatingsystem_is_linux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogramminglanguage',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
