# Generated by Django 4.2.2 on 2023-06-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossdb', '0008_alter_project_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
    ]
