# Generated by Django 4.1.7 on 2023-04-07 20:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('fossdb', '0001_initial'), ('fossdb', '0002_alter_projectprogramminglanguage_project'), ('fossdb', '0003_alter_project_licenses_and_more'), ('fossdb', '0004_alter_projectprogramminglanguage_percentage')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('licenses', models.ManyToManyField(related_name='projects', to='fossdb.license')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fossdb.programminglanguage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fossdb.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='programming_languages',
            field=models.ManyToManyField(related_name='projects', through='fossdb.ProjectProgrammingLanguage', to='fossdb.programminglanguage'),
        ),
        migrations.AlterField(
            model_name='projectprogramminglanguage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_languages', to='fossdb.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='licenses',
            field=models.ManyToManyField(to='fossdb.license'),
        ),
        migrations.AlterField(
            model_name='projectprogramminglanguage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fossdb.project'),
        ),
        migrations.AlterField(
            model_name='projectprogramminglanguage',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
