# Generated by Django 4.1.7 on 2023-04-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
        ('fossdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='License',
        ),
        migrations.AlterField(
            model_name='project',
            name='licenses',
            field=models.ManyToManyField(to='license.license'),
        ),
    ]
