# Generated by Django 4.2.2 on 2023-06-28 16:17

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile-pics/default.jpg', upload_to=account.models.get_profile_pic_path),
        ),
    ]
