# Generated by Django 4.2.2 on 2023-06-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
