# Generated by Django 4.2.2 on 2023-06-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossdb', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0007_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
