# Generated by Django 4.2.2 on 2023-06-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossdb', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0008_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
